version: "3.8"
services:
  test_web:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    image: web_testing
    volumes:
      - .:/app
    env_file:
      - .test.env
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=Test_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

volumes:
  postgres_data:
